// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseInventory.API.Context;

namespace WarehouseInventory.API.Migrations
{
    [DbContext(typeof(WarehouseInventoryContext))]
    [Migration("20200321012105_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarehouseInventory.API.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc49bab2-9151-4ce3-a9e9-66f171b7ce01"),
                            Amount = 20,
                            Description = "Comes in multiple shapes.",
                            Name = "Soap",
                            SellingPrice = 4.5,
                            Supplier = "Craig's Cleaning Factory."
                        },
                        new
                        {
                            Id = new Guid("af7156e0-1fef-45ac-8204-3b9afdc29888"),
                            Amount = 123,
                            Description = "Model paint",
                            Name = "Citedel paint",
                            SellingPrice = 8.5,
                            Supplier = "Games Workshop"
                        },
                        new
                        {
                            Id = new Guid("d02d36a9-edf2-429c-bc42-ef70a8a2eef5"),
                            Amount = 402,
                            Description = "Collectable card game packs",
                            Name = "Magic the Gathering Packs",
                            SellingPrice = 7.4000000000000004,
                            Supplier = "Wizards of the Coast"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
